name: Test
on: [pull_request]
jobs:
   size:
      runs-on: ubuntu-latest
      env:
         CI_JOB_NUMBER: 1
      steps:
         - uses: actions/checkout@v3
         - uses: pnpm/action-setup@v2
           with:
              version: 7
         - run: pnpm install --no-frozen-lockfile
         - run: pnpm build && pnpm test
